Release sts version 2.1.2.2
The sts version 2.1.2.2 code base dates back to 2015 Jun 29.

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -16,23 +16,30 @@ MKDIR= mkdir
 MAKEDEPEND= makedepend
 EGREP= egrep
 FGREP= fgrep
+VALGRIND= valgrind
+VALGRIND_OPTIONS= --leak-check=full --show-reachable=yes --tool=memcheck -v
+OSX_MALLOC_ENV= MallocGuardEdges=1 MallocStackLogging=1 MallocStackLoggingNoCompact=1 \
+    MallocScribble=1 MallocCheckHeapAbort=1 MallocErrorAbort=1 MallocCorruptionAbort=1
+TEE= tee
+INDENT= indent
+DIFF= diff
 
 # how to compile
 #
 OPT=
 DEBUG= -g3
 # XXX - release without -Werror: CFLAGS= -std=c99 -Wall -pedantic ${OPT} ${DEBUG}
+# XXX - release without -DDEBUG_LINT CFLAGS= -std=c99 -Wall -pedantic ${OPT} ${DEBUG}
+#CFLAGS= -std=c99 -Wall -Werror -pedantic -DDEBUG_LINT ${OPT} ${DEBUG}
 CFLAGS= -std=c99 -Wall -Werror -pedantic ${OPT} ${DEBUG}
 
 # locations
 #
 ROOTDIR= ..
-TEMPLATEDIR= ${ROOTDIR}/templates
 DATADIR= ${ROOTDIR}/data
 #
 DESTLIBDIR= /usr/local/lib/sts
 DESTBINDIR= /usr/local/bin
-DESTTEMPLATEDIR= ${DESTLIBDIR}/templates
 DESTDATADIR= ${DESTLIBDIR}/data
 
 # source
@@ -46,11 +53,12 @@ CSRC= assess.c frequency.c blockFrequency.c \
 	randomExcursionsVariant.c linearComplexity.c \
 	dfft.c cephes.c matrix.c \
 	utilities.c generators.c genutils.c \
-	Parse_args.c debug.c dyn_alloc.c
+	Parse_args.c debug.c dyn_alloc.c driver.c
 
-HSRC= cephes.h config.h decls.h defs.h \
+HSRC= cephes.h config.h defs.h \
 	dfft.h externs.h generators.h genutils.h \
-	matrix.h stat_fncs.h utilities.h
+	matrix.h stat_fncs.h utilities.h debug.h \
+	dyn_alloc.h
 
 SRCS= ${CSRC} ${HSRC}
 
@@ -63,35 +71,17 @@ OBJ= assess.o frequency.o blockFrequency.o \
       randomExcursionsVariant.o linearComplexity.o \
       dfft.o cephes.o matrix.o \
       utilities.o generators.o genutils.o \
-      Parse_args.o debug.o dyn_alloc.o
-
-# source data files
-#
-TEMPLATES= \
-	${TEMPLATEDIR}/template2 ${TEMPLATEDIR}/template3 \
-	${TEMPLATEDIR}/template4 ${TEMPLATEDIR}/template5 \
-	${TEMPLATEDIR}/template6 ${TEMPLATEDIR}/template7 \
-	${TEMPLATEDIR}/template8 ${TEMPLATEDIR}/template9 \
-	${TEMPLATEDIR}/template10 ${TEMPLATEDIR}/template11 \
-	${TEMPLATEDIR}/template12 ${TEMPLATEDIR}/template13 \
-	${TEMPLATEDIR}/template14 ${TEMPLATEDIR}/template15 \
-	${TEMPLATEDIR}/template16
+      Parse_args.o debug.o dyn_alloc.o driver.o
 
 DATA= ${DATADIR}/BBS.dat ${DATADIR}/data.bad_rng ${DATADIR}/data.e \
 	${DATADIR}/data.pi ${DATADIR}/data.sha1 ${DATADIR}/data.sqrt2 \
 	${DATADIR}/data.sqrt3
 
-# These template files are build from compressed source
-#
-BUILT_TEMPLATES= ${TEMPLATEDIR}/template17 \
-	${TEMPLATEDIR}/template18 ${TEMPLATEDIR}/template19 \
-	${TEMPLATEDIR}/template20 ${TEMPLATEDIR}/template21
-
 TARGETS= assess ../assess
 
 # default rule
 #
-all: ${TARGETS} ${TEMPLATES} ${BUILT_TEMPLATES} ${DATA}
+all: ${TARGETS} ${DATA}
 
 assess: ${OBJ}
 	${RM} -f $@
@@ -133,12 +123,10 @@ rank.o: rank.c
 discreteFourierTransform.o: discreteFourierTransform.c
 	${CC} -c -o $@ ${CFLAGS} discreteFourierTransform.c
 
-nonOverlappingTemplateMatchings.o: \
-    nonOverlappingTemplateMatchings.c
+nonOverlappingTemplateMatchings.o: nonOverlappingTemplateMatchings.c
 	${CC} -c -o $@ ${CFLAGS} nonOverlappingTemplateMatchings.c
 
-overlappingTemplateMatchings.o: \
-	overlappingTemplateMatchings.c
+overlappingTemplateMatchings.o: overlappingTemplateMatchings.c
 	${CC} -c -o $@ ${CFLAGS} overlappingTemplateMatchings.c
 
 universal.o: universal.c
@@ -180,28 +168,8 @@ generators.o: generators.c
 dyn_alloc.o: dyn_alloc.c
 	${CC} -c -o $@ ${CFLAGS} dyn_alloc.c
 
-# The larger templates are shipped compressed, uncompress
-# for use by sts
-#
-${TEMPLATEDIR}/template17: ${TEMPLATEDIR}/template17.Z
-	${RM} -f $@
-	${UNCOMPRESS} -d -f -c $? > $@
-
-${TEMPLATEDIR}/template18: ${TEMPLATEDIR}/template18.Z
-	${RM} -f $@
-	${UNCOMPRESS} -d -f -c $? > $@
-
-${TEMPLATEDIR}/template19: ${TEMPLATEDIR}/template19.Z
-	${RM} -f $@
-	${UNCOMPRESS} -d -f -c $? > $@
-
-${TEMPLATEDIR}/template20: ${TEMPLATEDIR}/template20.Z
-	${RM} -f $@
-	${UNCOMPRESS} -d -f -c $? > $@
-
-${TEMPLATEDIR}/template21: ${TEMPLATEDIR}/template21.Z
-	${RM} -f $@
-	${UNCOMPRESS} -d -f -c $? > $@
+driver.o: driver.c
+	${CC} -c -o $@ ${CFLAGS} driver.c
 
 # utility rules
 #
@@ -209,26 +177,122 @@ clean:
 	${RM} -f ${OBJ}
 
 clobber: clean
-	${RM} -f ${TARGETS}
-	${RM} -f tags makefile.bak
-	${RM} -f ${BUILT_TEMPLATES}
+	@for i in ${TARGETS} tags Makefile.bak; do \
+	    if [[ -e "$$i" ]]; then \
+		echo ${RM} -f "$$i"; \
+		${RM} -f "$$i"; \
+	    fi; \
+	done
+	@for i in valrun minivalrun osxmalloc miniosxmalloc; do \
+	    if [[ -e "$$i" ]]; then \
+		echo ${RM} -rf "$$i"; \
+		${RM} -rf "$$i"; \
+	    fi; \
+	done
+	@for i in $$(seq -w 01 15); do \
+	    if [[ -e "eachrun_$$i" ]]; then \
+		echo ${RM} -rf "eachrun_$$i"; \
+		${RM} -rf "eachrun_$$i"; \
+	    fi; \
+	done
+	@for i in ${SRCS}; do \
+	    if [[ -e "$$i"'~' ]]; then \
+		echo ${RM} -f "$$i"'~'; \
+		${RM} -f "$$i"'~'; \
+	    fi; \
+	done
 
 tags: ${SRC}
 	${RM} -f tags
 	@echo "${CTAGS} ${SRCS}"
-	@-${CTAGS} ${SRCS} 2>&1 | \
-	    ${EGREP} -v 'Second entry ignored|Duplicate entry in file config.h'
+	${CTAGS} ${SRCS}
 
 ctags: tags
+
+picky: ${SRCS}
+	picky -v -w132 ${SRCS}
+	@if grep -l '[	 ]$$' ${SRCS} >/dev/null; then \
+	    echo ; \
+	    echo "also found bogus tabs and/or spaces in:"; \
+	    grep -l '[	 ]$$' ${SRCS}; \
+	    exit 1; \
+	fi
+
+indent: ${SRCS}
+	@for i in ${SRCS}; do \
+	    ${RM} -f "$$i"'~'; \
+	    ${INDENT} "$$i"; \
+	    if ${CMP} -s "$$i"'~' "$$i"; then \
+		${RM} -f "$$i"'~'; \
+	    else \
+		echo "=-= indent changed $$i =-="; \
+		${DIFF} -u "$$i"'~' "$$i"; \
+	    fi; \
+	done
+
+valgrind: assess
+	${RM} -rf valrun
+	${MKDIR} valrun
+	${VALGRIND} ${VALGRIND_OPTIONS} ./assess -b -i 20 -g 4 -I 1 -w valrun -v 3 1000000 2>&1 | \
+		${TEE} valrun/valgrind.out
+
+valgrindeach: assess
+	@for i in $$(seq -w 01 15); do \
+	    if [[ -e "eachrun_$$i" ]]; then \
+		echo ${RM} -rf "eachrun_$$i"; \
+		${RM} -rf "eachrun_$$i"; \
+	    fi; \
+	done
+	for i in $$(seq -w 01 15); do \
+	    ${MKDIR} -p "eachrun_$$i"; \
+	    ${VALGRIND} ${VALGRIND_OPTIONS} ./assess -b -t "$$i" -i 20 -g 4 -I 1 -w "eachrun_$$i" -v 3 1000000 2>&1 | \
+		    ${TEE} eachrun_$$i/valgrind.out; \
+	done
+
+minivalgrind: assess
+	${RM} -rf minivalrun
+	${MKDIR} minivalrun
+	${VALGRIND} ${VALGRIND_OPTIONS} ./assess -b -i 2 -g 4 -I 1 -w minivalrun -v 3 1000000 2>&1 | \
+		${TEE} minivalrun/valgrind.out
+
+osxtest: assess
+	${RM} -rf osxmalloc osxmalloc/malloc.out
+	${MKDIR} -p osxmalloc
+	${OSX_MALLOC_ENV} MallocStackLoggingDirectory=osxmalloc \
+	  MallocLogFile=osxmalloc/malloc.out \
+	  ./assess -b -i 20 -g 4 -I 1 -w osxmalloc -v 3 1000000
+	@if [[ -f osxmalloc/malloc.out && -s osxmalloc/malloc.out ]]; then \
+	    echo "=-=-= malloc error log follows"; \
+	    cat osxmalloc/malloc.out; \
+	    echo "=-=-= malloc error log preceeds"; \
+	else \
+	    echo "=-=-= no osxmalloc/malloc.out data, removing =-=-="; \
+	    rm -f osxmalloc/malloc.out; \
+	fi
+
+miniosxtest: assess
+	${RM} -rf miniosxmalloc miniosxmalloc/malloc.out
+	${MKDIR} -p miniosxmalloc
+	${OSX_MALLOC_ENV} MallocStackLoggingDirectory=miniosxmalloc \
+	  MallocLogFile=miniosxmalloc/malloc.out \
+	  ./assess -b -i 2 -g 4 -I 1 -w miniosxmalloc -v 3 1000000
+	@if [[ -f miniosxmalloc/malloc.out && -s miniosxmalloc/malloc.out ]]; then \
+	    echo "=-=-= malloc error log follows"; \
+	    cat miniosxmalloc/malloc.out; \
+	    echo "=-=-= malloc error log preceeds"; \
+	else \
+	    echo "=-=-= no miniosxmalloc/malloc.out data, removing =-=-="; \
+	    rm -f miniosxmalloc/malloc.out; \
+	fi
 
 rebuild: clobber assess
 
 depend:
 	@${RM} -f Makefile.bak
-	@echo "${MAKEDEPEND} -I. -Y -- ${CFLAGS} -- ${SRCS}"
-	@-${MAKEDEPEND} -I. -Y -- ${CFLAGS} -- ${SRCS} 2>&1 | \
-	    ${EGREP} -v 'string.h|stdlib.h|stdio.h|errno.h|stdarg.h|getopt.h' | \
-	    ${EGREP} -v 'time.h|math.h|sys/types.h|unistd.h|fcntl.h|sys/stat.h'
+	@echo "${MAKEDEPEND} -I. -Y -- ${CFLAGS} -- ${CSRC}"
+	@-${MAKEDEPEND} -I. -Y -- ${CFLAGS} -- ${CSRC} 2>&1 | \
+	    ${EGREP} -v 'string\.h|stdlib\.h|stdio\.h|errno\.h|stdarg\.h|getopt\.h|limits\.h' | \
+	    ${EGREP} -v 'time\.h|math\.h|sys/types\.h|unistd\.h|fcntl\.h|sys/stat\.h'
 	@-if ${CMP} -s Makefile Makefile.bak; then \
 	    echo "${MAKEDEPEND} did not change anything, backup not needed"; \
 	    echo ${RM} -f Makefile.bak; \
@@ -245,46 +309,53 @@ install: all
 	if [ ! -d "${DESTBINDIR}" ]; then \
 	    ${MKDIR} -p "${DESTBINDIR}"; \
 	fi
-	if [ ! -d "${DESTTEMPLATEDIR}" ]; then \
-	    ${MKDIR} -p "${DESTTEMPLATEDIR}"; \
-	fi
 	if [ ! -d "${DESTDATADIR}" ]; then \
 	    ${MKDIR} -p "${DESTDATADIR}"; \
 	fi
 	${INSTALL} -c -m 0755 assess ${DESTBINDIR}
-	${INSTALL} -m 0444 ${TEMPLATES} ${DESTTEMPLATEDIR}
 	${INSTALL} -m 0444 ${DATA} ${DESTDATADIR}
 
 # DO NOT DELETE THIS LINE -- make depend depends on it.
 
-assess.o: defs.h config.h cephes.h utilities.h stat_fncs.h
-frequency.o: externs.h defs.h config.h utilities.h
-blockFrequency.o: externs.h defs.h config.h cephes.h utilities.h
-cusum.o: externs.h defs.h config.h cephes.h utilities.h
-runs.o: externs.h defs.h config.h cephes.h utilities.h
-longestRunOfOnes.o: externs.h defs.h config.h cephes.h utilities.h
-serial.o: externs.h defs.h config.h cephes.h utilities.h
-rank.o: externs.h defs.h config.h cephes.h matrix.h utilities.h
-discreteFourierTransform.o: externs.h defs.h config.h utilities.h cephes.h
-discreteFourierTransform.o: dfft.h
-nonOverlappingTemplateMatchings.o: externs.h defs.h config.h utilities.h
-nonOverlappingTemplateMatchings.o: cephes.h
-overlappingTemplateMatchings.o: externs.h defs.h config.h utilities.h
-overlappingTemplateMatchings.o: cephes.h
-universal.o: externs.h defs.h config.h utilities.h cephes.h
-approximateEntropy.o: externs.h defs.h config.h utilities.h cephes.h
-randomExcursions.o: externs.h defs.h config.h cephes.h utilities.h
-randomExcursionsVariant.o: externs.h defs.h config.h cephes.h utilities.h
-linearComplexity.o: externs.h defs.h config.h cephes.h utilities.h
+assess.o: defs.h config.h dyn_alloc.h cephes.h utilities.h stat_fncs.h
+assess.o: externs.h debug.h
+frequency.o: externs.h defs.h config.h dyn_alloc.h utilities.h debug.h
+frequency.o: cephes.h
+blockFrequency.o: externs.h defs.h config.h dyn_alloc.h cephes.h utilities.h
+blockFrequency.o: debug.h
+cusum.o: externs.h defs.h config.h dyn_alloc.h cephes.h utilities.h debug.h
+runs.o: externs.h defs.h config.h dyn_alloc.h cephes.h utilities.h debug.h
+longestRunOfOnes.o: externs.h defs.h config.h dyn_alloc.h cephes.h
+longestRunOfOnes.o: utilities.h debug.h
+serial.o: externs.h defs.h config.h dyn_alloc.h cephes.h utilities.h debug.h
+rank.o: externs.h defs.h config.h dyn_alloc.h cephes.h matrix.h utilities.h
+rank.o: debug.h
+discreteFourierTransform.o: externs.h defs.h config.h dyn_alloc.h utilities.h
+discreteFourierTransform.o: cephes.h dfft.h debug.h
+nonOverlappingTemplateMatchings.o: externs.h defs.h config.h dyn_alloc.h
+nonOverlappingTemplateMatchings.o: utilities.h cephes.h debug.h
+overlappingTemplateMatchings.o: externs.h defs.h config.h dyn_alloc.h
+overlappingTemplateMatchings.o: utilities.h cephes.h debug.h
+universal.o: externs.h defs.h config.h dyn_alloc.h utilities.h cephes.h
+universal.o: debug.h
+approximateEntropy.o: externs.h defs.h config.h dyn_alloc.h utilities.h
+approximateEntropy.o: cephes.h debug.h
+randomExcursions.o: externs.h defs.h config.h dyn_alloc.h cephes.h
+randomExcursions.o: utilities.h debug.h
+randomExcursionsVariant.o: externs.h defs.h config.h dyn_alloc.h cephes.h
+randomExcursionsVariant.o: utilities.h debug.h
+linearComplexity.o: externs.h defs.h config.h dyn_alloc.h cephes.h
+linearComplexity.o: utilities.h debug.h
 dfft.o: dfft.h
-cephes.o: cephes.h defs.h config.h
-matrix.o: externs.h defs.h config.h matrix.h
-utilities.o: externs.h defs.h config.h utilities.h generators.h stat_fncs.h
-generators.o: externs.h defs.h config.h utilities.h generators.h genutils.h
-genutils.o: genutils.h config.h
-Parse_args.o: externs.h defs.h config.h utilities.h
-debug.o: externs.h defs.h config.h
-dyn_alloc.o: defs.h config.h
-defs.o: config.h
-externs.o: defs.h config.h
-genutils.o: config.h
+cephes.o: cephes.h defs.h config.h dyn_alloc.h externs.h debug.h
+matrix.o: externs.h defs.h config.h dyn_alloc.h matrix.h debug.h
+utilities.o: externs.h defs.h config.h dyn_alloc.h utilities.h generators.h
+utilities.o: stat_fncs.h debug.h
+generators.o: externs.h defs.h config.h dyn_alloc.h utilities.h generators.h
+generators.o: genutils.h debug.h
+genutils.o: genutils.h config.h debug.h
+Parse_args.o: externs.h defs.h config.h dyn_alloc.h utilities.h debug.h
+debug.o: debug.h externs.h defs.h config.h dyn_alloc.h
+dyn_alloc.o: dyn_alloc.h debug.h
+driver.o: defs.h config.h dyn_alloc.h utilities.h debug.h stat_fncs.h
+driver.o: externs.h
